name: test-coverage

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.x'
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev
      - name: Run tests and generate coverage report
        run: |
          poetry run coverage run manage.py test
          poetry run coverage xml
      - name: Test code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: poetry run coverage xml
          coverageLocations: "coverage.xml"
          coverageInputType: "coverage.py"
          debug: true
